### ISSUE TITLE
Streaming set never shows up

### ISSUE THREAD

**Issue by RobertWakefieldCarl** [MyPureCloud/analytics-hub#1]
I have tried using analytics-hub, but the streaming sets never show up in my workspace.  What is the secret to getting this working?

**Comment by RobertWakefieldCarl** [comment]
I get this error:
wabi-west-us-redirect.analysis.windows.net/powerbi/resource/userPhoto/?huid=1697976615 Failed to load resource: the server responded with a status of 400 (Bad Request)

But that is just for the photo file. 

Nothing else ever shows up in Console

**Comment by szlaskidaniel** [comment]
It was permission issue.
Extend your permissions (include there Engage Supervisor) - that helped
